""" Update message table 
Revision ID: 205f59f8d860
Revises: d0b91b82a37f
Create Date: 2024-07-29 16:35:10.309901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '205f59f8d860'
down_revision: Union[str, None] = 'd0b91b82a37f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chatbot_knowledge_knowledge_id_fkey', 'chatbot_knowledge', type_='foreignkey')
    op.drop_constraint('chatbot_knowledge_chatbot_id_fkey', 'chatbot_knowledge', type_='foreignkey')
    op.create_foreign_key(None, 'chatbot_knowledge', 'knowledge', ['knowledge_id'], ['id'])
    op.create_foreign_key(None, 'chatbot_knowledge', 'chatbot', ['chatbot_id'], ['id'])
    op.drop_constraint('config_llm_chatbot_id_fkey', 'config_llm', type_='foreignkey')
    op.create_foreign_key(None, 'config_llm', 'chatbot', ['chatbot_id'], ['id'])
    op.alter_column('embed_type', 'knowledge_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_embed_type_id', table_name='embed_type')
    op.drop_column('embed_type', 'id')
    op.add_column('file', sa.Column('size', sa.Integer(), nullable=True))
    op.drop_column('knowledge', 'segment')
    op.add_column('message', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('message', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('message', sa.Column('latency', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'latency')
    op.drop_column('message', 'output_tokens')
    op.drop_column('message', 'input_tokens')
    op.add_column('knowledge', sa.Column('segment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('file', 'size')
    op.add_column('embed_type', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_embed_type_id', 'embed_type', ['id'], unique=False)
    op.alter_column('embed_type', 'knowledge_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'config_llm', type_='foreignkey')
    op.create_foreign_key('config_llm_chatbot_id_fkey', 'config_llm', 'chatbot', ['chatbot_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'chatbot_knowledge', type_='foreignkey')
    op.drop_constraint(None, 'chatbot_knowledge', type_='foreignkey')
    op.create_foreign_key('chatbot_knowledge_chatbot_id_fkey', 'chatbot_knowledge', 'chatbot', ['chatbot_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('chatbot_knowledge_knowledge_id_fkey', 'chatbot_knowledge', 'knowledge', ['knowledge_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
