"""edit knowledge, embed_type table

Revision ID: 2e1d1fda780c
Revises: bfcf0e9d5d92
Create Date: 2024-07-26 08:52:35.670683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e1d1fda780c'
down_revision: Union[str, None] = 'bfcf0e9d5d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column('document', 'index',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.add_column('embed_type', sa.Column('type', sa.String(), nullable=True))
    op.add_column('knowledge', sa.Column('size', sa.Integer(), nullable=True))
    op.add_column('knowledge', sa.Column('segment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge', 'segment')
    op.drop_column('knowledge', 'size')
    op.drop_column('embed_type', 'type')
    op.alter_column('document', 'index',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
