"""edit delete cascade in knowledge table

Revision ID: 7aacfaac76b1
Revises: f5e335e68b42
Create Date: 2024-08-13 17:03:07.545814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aacfaac76b1'
down_revision: Union[str, None] = 'f5e335e68b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('knowledge_user_id_fkey', 'knowledge', type_='foreignkey')
    op.create_foreign_key('knowledge_user_id_fkey', 'knowledge', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.execute('''INSERT INTO storage.buckets (id, name)
                VALUES
                ('avatar', 'avatar'),
                ('file', 'file');''')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('knowledge_user_id_fkey', 'knowledge', type_='foreignkey')
    op.create_foreign_key('knowledge_user_id_fkey', 'knowledge', 'users', ['user_id'], ['id'], referent_schema='auth')
    op.execute('''DELETE FROM storage.buckets
                WHERE id = 'avatar' OR id = 'file';''')
    # ### end Alembic commands ###
