"""add column index in document table

Revision ID: 90351535f3f4
Revises: 346a9e5d548e
Create Date: 2024-07-23 13:15:24.978025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90351535f3f4'
down_revision: Union[str, None] = '346a9e5d548e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('index', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'index')
    # ### end Alembic commands ###
