""" add ondelete cascade to config_llm and chatbot_knowledge

Revision ID: a3e345e8b69a
Revises: 5d6646dec686
Create Date: 2024-07-29 17:28:29.833918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3e345e8b69a'
down_revision: Union[str, None] = '5d6646dec686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('config_llm_chatbot_id_fkey', 'config_llm', type_='foreignkey')
    op.create_foreign_key('config_llm_chatbot_id_fkey', 'config_llm', 'chatbot', ['chatbot_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('chatbot_knowledge_chatbot_id_fkey', 'chatbot_knowledge', type_='foreignkey')
    op.drop_constraint('chatbot_knowledge_knowledge_id_fkey', 'chatbot_knowledge', type_='foreignkey')
    op.create_foreign_key('chatbot_knowledge_chatbot_id_fkey', 'chatbot_knowledge', 'chatbot', ['chatbot_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('chatbot_knowledge_knowledge_id_fkey', 'chatbot_knowledge', 'knowledge', ['knowledge_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('message_chatbot_id_fkey', 'message', type_='foreignkey')
    op.create_foreign_key('message_chatbot_id_fkey', 'message', 'chatbot', ['chatbot_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chatbot_knowledge_knowledge_id_fkey', 'chatbot_knowledge', type_='foreignkey')
    op.drop_constraint('chatbot_knowledge_chatbot_id_fkey', 'chatbot_knowledge', type_='foreignkey')
    op.drop_constraint('message_chatbot_id_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'chatbot', ['chatbot_id'], ['id'])
    op.create_foreign_key(None, 'chatbot_knowledge', 'chatbot', ['chatbot_id'], ['id'])
    op.create_foreign_key(None, 'chatbot_knowledge', 'knowledge', ['knowledge_id'], ['id'])
    op.drop_constraint('config_llm_chatbot_id_fkey', 'config_llm', type_='foreignkey')
    op.create_foreign_key(None, 'config_llm', 'chatbot', ['chatbot_id'], ['id'])
    # ### end Alembic commands ###

