"""Add 4 table and enable row level security

Revision ID: bfcf0e9d5d92
Revises: 90351535f3f4
Create Date: 2024-07-24 09:23:49.071303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfcf0e9d5d92'
down_revision: Union[str, None] = '90351535f3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('favourite', sa.Boolean(), nullable=True),
    sa.Column('llm_name', sa.String(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'],ondelete='CASCADE')
    )
    op.create_index(op.f('ix_chatbot_id'), 'chatbot', ['id'], unique=False)
    op.create_table('chatbot_knowledge',
    sa.Column('chatbot_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbot.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chatbot_id', 'knowledge_id')
    )
    op.create_table('config_llm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('top_p', sa.Float(), nullable=True),
    sa.Column('frequency_penalty', sa.Float(), nullable=True),
    sa.Column('presence_penalty', sa.Float(), nullable=True),
    sa.Column('dialog_round', sa.Integer(), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('output_format', sa.String(), nullable=True),
    sa.Column('config_type', sa.String(), nullable=True),
    sa.Column('llm_name', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('info', sa.String(), nullable=True),
    sa.Column('chatbot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_llm_id'), 'config_llm', ['id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('chatbot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    op.execute("alter table chatbot enable row level security;")
    op.execute("alter table chatbot_knowledge enable row level security;")
    op.execute("alter table config_llm enable row level security;")
    op.execute("alter table message enable row level security;")
    op.execute("alter table knowledge enable row level security;")
    op.execute("alter table embed_type enable row level security;")
    op.execute("alter table file enable row level security;")
    op.execute("alter table document enable row level security;")
    op.create_foreign_key('knowledge_user_id_fkey', 'knowledge', 'users', ['user_id'], ['id'], referent_schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_config_llm_id'), table_name='config_llm')
    op.drop_table('config_llm')
    op.drop_table('chatbot_knowledge')
    op.drop_index(op.f('ix_chatbot_id'), table_name='chatbot')
    op.drop_table('chatbot')
    # ### end Alembic commands ###
