"""edit table document 

Revision ID: d0b91b82a37f
Revises: 2e1d1fda780c
Create Date: 2024-07-29 15:35:47.061377

"""
from typing import Sequence, Union
import pgvector
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0b91b82a37f'
down_revision: Union[str, None] = '2e1d1fda780c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'vector')
    op.add_column('document', sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'vector')
    op.add_column('document', sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    # ### end Alembic commands ###
