"""add cloumn metedata in document table

Revision ID: e0e40cc66ec4
Revises: 8c95ab593e47
Create Date: 2024-07-22 14:55:43.056636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0e40cc66ec4'
down_revision: Union[str, None] = '8c95ab593e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('meta_data', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'meta_data')
    # ### end Alembic commands ###
