"""add fuction retrieval

Revision ID: 5802d308c93d
Revises: df45152b4e97
Create Date: 2024-08-22 13:37:05.209073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5802d308c93d'
down_revision: Union[str, None] = 'df45152b4e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""CREATE OR REPLACE FUNCTION match_documents_7 (
                query_embedding VECTOR(768),
                knowledge_ids INT[]
                ) RETURNS TABLE (
                content TEXT,
                similarity FLOAT,
                file_id INT,
                index INT
                ) LANGUAGE plpgsql AS $$
                BEGIN
                RETURN QUERY
                SELECT 
                    document.content::TEXT,  -- Rõ ràng chỉ định cột từ bảng
                    1 - (document.vector <=> query_embedding) AS similarity,
                    document.file_id,
                    document.index
                FROM document
                WHERE document.knowledge_id = ANY(knowledge_ids)
                ORDER BY document.vector <=> query_embedding
                LIMIT 20;
                END;
                $$;""")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DROP FUNCTION IF EXISTS match_documents_7 (
                query_embedding VECTOR(768),
                knowledge_ids INT[]
                );""")
    # ### end Alembic commands ###
