"""add fuction

Revision ID: b9b39842502b
Revises: 5286c4cbd774
Create Date: 2024-08-20 17:52:25.714412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9b39842502b'
down_revision: Union[str, None] = '5286c4cbd774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""CREATE OR REPLACE FUNCTION update_document_indices(f_id INT, i INT)
                RETURNS VOID LANGUAGE plpgsql AS $$
                BEGIN
                    UPDATE document
                    SET index = index + 1
                    WHERE document.file_id = f_id
                    AND document.index >= i;
                END;
                $$;""")
    op.execute("""CREATE OR REPLACE FUNCTION match_documents_4 (
                query_embedding VECTOR(1536),
                knowledge_ids INT[]
                ) RETURNS TABLE (
                content TEXT,
                similarity FLOAT
                ) LANGUAGE plpgsql AS $$
                BEGIN
                RETURN QUERY
                SELECT 
                    document.content::TEXT,  -- Rõ ràng chỉ định cột từ bảng
                    1 - (document.vector <=> query_embedding) AS similarity
                FROM document
                WHERE document.knowledge_id = ANY(knowledge_ids)
                ORDER BY document.vector <=> query_embedding
                LIMIT 20;
                END;
                $$;""")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DROP FUNCTION IF EXISTS match_documents_4 (
                query_embedding VECTOR(1536),
                knowledge_ids INT[]
                );""")
    op.execute("DROP FUNCTION IF EXISTS changepassword(TEXT, TEXT, UUID);")
    # ### end Alembic commands ###
